### ISSUE TITLE
Train with larger dataset from pretrained checkpoint

### ISSUE THREAD

**Issue by nguyenhuylan** [google-research/deeplab2#100]
Thank you for the great work.

I want to train with my own dataset that has 37 classes. I can train with ImageNet pretrained checkpoint correctly. But when I used Cityscapes pretrained checkpoint (19 classes), I got this error:

ValueError: Tensor's shape (1, 1, 256, 37) is not compatible with supplied shape (1, 1, 256, 19)

**Comment by aquariusjay** [comment]
Hi @nguyenhuylan,

Thanks for reporting the issue.
The error happens because the mistmatch between the last 1x1 convolution layer pretrained on Cityscapes (19 classes) and the last 1x1 convolution used in your current dataset (37 classes).
You could set [restore_semantic_last_layer_from_initial_checkpoint](https://github.com/google-research/deeplab2/blob/58eadb39d02c19ec9b3cfb1beab2108cd5897c7f/model.proto#L201) to false in the config, which will not load the pretrained last 1x1 convolution.

Cheers,

**Comment by nguyenhuylan** [comment]
Thank you!
I can train my dataset from Cityscapes pretrained checkpoint now. 

I close this issue.
