### ISSUE TITLE
About pretraining with Mapillary Vistas 

### ISSUE THREAD

**Issue by pingjun18-li** [google-research/deeplab2#26]
Hi, thanks for you codes. And I have a question about pretrain on Mapillary Vistas.
It is general to pretrain with Mapillary Vistas and fine-tune on Cityscapes. The thing and stuff categories are quite different for these two data sets, is there some special treatment required?
Especially, some things (e.g. traffic lights, poles) in Mapillary Vistas are marked as stuff in Cityscapes, how you deal with such categories?

**Comment by aquariusjay** [comment]
Hi pingjun18-li,

Thanks for the question.
For the Mapillary Vistas pretraining, we do not do anything special, except that we resize the image's longest side to either 2177 (as the Panoptic-DeepLab [paper](https://arxiv.org/pdf/1911.10194.pdf)) or 2049 (as the SWideRNet [paper](https://arxiv.org/pdf/2011.11675.pdf)), in order to handle the large resolution variation in Mapillary Vistas images.
The resizing can be done in the codebase by setting min_resize_value = max_resize_value = 2177 (or 2049).
When fine-tuning on the Cityscapes, the last prediction layer is removed and randomly initialized.

What you proposed there to specially handle the classes may benefit the fine-tuning. But, we have not explored that.

Cheers,

**Comment by aquariusjay** [comment]
Closing the issue, as it has nothing to do with the library itself.
Please feel free to open a new one if you have questions about the DeepLab2 library.
Thanks.
