### ISSUE TITLE
Random input order

### ISSUE THREAD

**Issue by lxa9867** [google-research/deeplab2#28]
Hi,

I found a bug in the dataloader which results in random input order. 

The dataset is initialized by `dataset = tf.data.Dataset.list_files(self._file_pattern)` while it is decorated by `eval_dataset = orbit.utils.make_distributed_dataset(self._strategy, eval_dataset)`. In distributed running, the input order will be broken. To keep correct order,  it should be initialized by `dataset = tf.data.Dataset.list_files(self._file_pattern, shuffle=False)`.

**Comment by aquariusjay** [comment]
Hi lxa9867,

Thanks for reporting the issue.
May I ask why you need to keep the image input order during evaluation?

Cheers,

**Comment by lxa9867** [comment]
I just found this when I visualized the result of different training configs. The results seem random thus I cannot compare them. I leave this as a note for those who want to visualize the results.

**Comment by aquariusjay** [comment]
Hi lxa9867,

I see your point and thanks for bringing it up.
Indeed, there is some randomness during visualization since the default setting only shows 10 images (i.e., random 10 images).
We could do as what you proposed to always visualize the same 10 images by setting `shuffle=False` during evaluation.
Would you like to prepare a PR for that?

Cheers,

**Comment by aquariusjay** [comment]
Hi lxa9867,

Thanks for reporting the issue.
We will update the code to reflect this change soon (deterministic behavior for visualization).

Cheers,

**Comment by ClaireXie** [comment]
Thanks for the issue report. Fix has been updated in https://github.com/google-research/deeplab2/commit/5643ddfff25631be3eadd1d7a8192801f36fe75e.
